/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.4-dev at Sat Aug  1 08:31:22 2015. */

#ifndef PB_SOTH_PB_H_INCLUDED
#define PB_SOTH_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
/* Struct definitions */
typedef struct _LedBrightness {
    uint32_t red;
    uint32_t green;
    uint32_t blue;
} LedBrightness;

typedef struct _ServoPosition {
    int32_t servo_front_right;
    int32_t servo_front_left;
    int32_t servo_back_right;
    int32_t servo_back_left;
    int32_t servo_yaw;
} ServoPosition;

typedef struct _WeatherData {
    float humidity;
    float pressure;
    float temperature;
} WeatherData;

/* Default values for struct fields */

/* Initializer values for message structs */
#define ServoPosition_init_default               {0, 0, 0, 0, 0}
#define LedBrightness_init_default               {0, 0, 0}
#define WeatherData_init_default                 {0, 0, 0}
#define ServoPosition_init_zero                  {0, 0, 0, 0, 0}
#define LedBrightness_init_zero                  {0, 0, 0}
#define WeatherData_init_zero                    {0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define LedBrightness_red_tag                    1
#define LedBrightness_green_tag                  2
#define LedBrightness_blue_tag                   3
#define ServoPosition_servo_front_right_tag      1
#define ServoPosition_servo_front_left_tag       2
#define ServoPosition_servo_back_right_tag       3
#define ServoPosition_servo_back_left_tag        4
#define ServoPosition_servo_yaw_tag              5
#define WeatherData_humidity_tag                 1
#define WeatherData_pressure_tag                 2
#define WeatherData_temperature_tag              3

/* Struct field encoding specification for nanopb */
extern const pb_field_t ServoPosition_fields[6];
extern const pb_field_t LedBrightness_fields[4];
extern const pb_field_t WeatherData_fields[4];

/* Maximum encoded size of messages (where known) */
#define ServoPosition_size                       55
#define LedBrightness_size                       18
#define WeatherData_size                         15

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define SOTH_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
