/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.4-dev at Sat Aug  1 01:21:45 2015. */

#include "soth.pb.h"

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t SetServoPosition_fields[6] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, SetServoPosition, servo_front_right, servo_front_right, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, SetServoPosition, servo_front_left, servo_front_right, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, SetServoPosition, servo_back_right, servo_front_left, 0),
    PB_FIELD(  4, INT32   , REQUIRED, STATIC  , OTHER, SetServoPosition, servo_back_left, servo_back_right, 0),
    PB_FIELD(  5, INT32   , REQUIRED, STATIC  , OTHER, SetServoPosition, servo_yaw, servo_back_left, 0),
    PB_LAST_FIELD
};

const pb_field_t SetLedBrightness_fields[4] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, SetLedBrightness, red, red, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, SetLedBrightness, green, red, 0),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, SetLedBrightness, blue, green, 0),
    PB_LAST_FIELD
};


