/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.4-dev at Sat Aug  1 01:21:45 2015. */

#ifndef PB_SOTH_PB_H_INCLUDED
#define PB_SOTH_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
/* Struct definitions */
typedef struct _SetLedBrightness {
    uint32_t red;
    uint32_t green;
    uint32_t blue;
} SetLedBrightness;

typedef struct _SetServoPosition {
    int32_t servo_front_right;
    int32_t servo_front_left;
    int32_t servo_back_right;
    int32_t servo_back_left;
    int32_t servo_yaw;
} SetServoPosition;

/* Default values for struct fields */

/* Initializer values for message structs */
#define SetServoPosition_init_default            {0, 0, 0, 0, 0}
#define SetLedBrightness_init_default            {0, 0, 0}
#define SetServoPosition_init_zero               {0, 0, 0, 0, 0}
#define SetLedBrightness_init_zero               {0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define SetLedBrightness_red_tag                 1
#define SetLedBrightness_green_tag               2
#define SetLedBrightness_blue_tag                3
#define SetServoPosition_servo_front_right_tag   1
#define SetServoPosition_servo_front_left_tag    2
#define SetServoPosition_servo_back_right_tag    3
#define SetServoPosition_servo_back_left_tag     4
#define SetServoPosition_servo_yaw_tag           5

/* Struct field encoding specification for nanopb */
extern const pb_field_t SetServoPosition_fields[6];
extern const pb_field_t SetLedBrightness_fields[4];

/* Maximum encoded size of messages (where known) */
#define SetServoPosition_size                    55
#define SetLedBrightness_size                    18

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define SOTH_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
