/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.4-dev at Sat Aug  1 08:31:22 2015. */

#include "soth.pb.h"

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t ServoPosition_fields[6] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, ServoPosition, servo_front_right, servo_front_right, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, ServoPosition, servo_front_left, servo_front_right, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, ServoPosition, servo_back_right, servo_front_left, 0),
    PB_FIELD(  4, INT32   , REQUIRED, STATIC  , OTHER, ServoPosition, servo_back_left, servo_back_right, 0),
    PB_FIELD(  5, INT32   , REQUIRED, STATIC  , OTHER, ServoPosition, servo_yaw, servo_back_left, 0),
    PB_LAST_FIELD
};

const pb_field_t LedBrightness_fields[4] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, LedBrightness, red, red, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, LedBrightness, green, red, 0),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, LedBrightness, blue, green, 0),
    PB_LAST_FIELD
};

const pb_field_t WeatherData_fields[4] = {
    PB_FIELD(  1, FLOAT   , REQUIRED, STATIC  , FIRST, WeatherData, humidity, humidity, 0),
    PB_FIELD(  2, FLOAT   , REQUIRED, STATIC  , OTHER, WeatherData, pressure, humidity, 0),
    PB_FIELD(  3, FLOAT   , REQUIRED, STATIC  , OTHER, WeatherData, temperature, pressure, 0),
    PB_LAST_FIELD
};


