/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.3 at Sun Jun 21 03:57:39 2015. */

#ifndef PB_SOTH_PB_H_INCLUDED
#define PB_SOTH_PB_H_INCLUDED
#include "pb.h"

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
/* Struct definitions */
typedef struct _RobotInfoResponse {
    pb_callback_t name;
} RobotInfoResponse;

typedef struct _RobotInfoRequest {
    int32_t robot_id;
} RobotInfoRequest;

/* Default values for struct fields */

/* Initializer values for message structs */
#define RobotInfoRequest_init_default            {0}
#define RobotInfoResponse_init_default           {{{NULL}, NULL}}
#define RobotInfoRequest_init_zero               {0}
#define RobotInfoResponse_init_zero              {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define RobotInfoResponse_name_tag               1
#define RobotInfoRequest_robot_id_tag            1

/* Struct field encoding specification for nanopb */
extern const pb_field_t RobotInfoRequest_fields[2];
extern const pb_field_t RobotInfoResponse_fields[2];

/* Maximum encoded size of messages (where known) */
#define RobotInfoRequest_size                    11

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define SOTH_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
