/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.3 at Sun Jun 21 03:57:39 2015. */

#include "soth.pb.h"

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t RobotInfoRequest_fields[2] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, RobotInfoRequest, robot_id, robot_id, 0),
    PB_LAST_FIELD
};

const pb_field_t RobotInfoResponse_fields[2] = {
    PB_FIELD(  1, STRING  , REQUIRED, CALLBACK, FIRST, RobotInfoResponse, name, name, 0),
    PB_LAST_FIELD
};


